name: bayesian_toa_project
channels:
  - conda-forge
  - defaults
dependencies:
  - arviz=0.4.1
  - numpy=1.16.4
  - pandas=0.24.2
  - pymc3=3.7
  - python=3.7.1
  - scikit-learn=0.20.2
  - seaborn=0.9.0

